/**
 * Ticketing Integration — pushes scan findings to Jira, GitHub Issues, or Linear.
 *
 * Supports:
 * - Jira Cloud REST API v3
 * - GitHub Issues API
 * - Linear GraphQL API
 *
 * Features:
 * - Severity filtering (minSeverity threshold)
 * - Deduplication via title + target matching
 * - Trend-aware commenting (persisting/resolved findings)
 * - Dry-run mode
 */

import type { ScanFinding } from "../drizzle/schema";
import type { BusinessImpact, AttackTechnique } from "./findingEnrichment";

// ─── Configuration Types ─────────────────────────────────────────────────────

export interface JiraConfig {
  enabled: boolean;
  baseUrl: string;
  projectKey: string;
  apiToken: string;
  email: string;
  minSeverity: "critical" | "high" | "medium" | "low";
  issueType?: string;
  labels?: string[];
  deduplication?: boolean;
  reopenResolved?: boolean;
}

export interface GitHubConfig {
  enabled: boolean;
  repo: string;
  token: string;
  minSeverity: "critical" | "high" | "medium" | "low";
  labels?: string[];
}

export interface LinearConfig {
  enabled: boolean;
  apiKey: string;
  teamId: string;
  minSeverity: "critical" | "high" | "medium" | "low";
}

export interface IntegrationsConfig {
  jira?: JiraConfig;
  github?: GitHubConfig;
  linear?: LinearConfig;
}

export interface TicketResult {
  provider: "jira" | "github" | "linear";
  action: "created" | "updated" | "commented" | "reopened" | "skipped";
  findingTitle: string;
  ticketKey?: string;
  ticketUrl?: string;
  reason?: string;
}

// ─── Severity Ordering ───────────────────────────────────────────────────────

const SEVERITY_RANK: Record<string, number> = {
  critical: 4, high: 3, medium: 2, low: 1, info: 0,
};

export function meetsMinSeverity(severity: string, minSeverity: string): boolean {
  return (SEVERITY_RANK[severity] ?? 0) >= (SEVERITY_RANK[minSeverity] ?? 0);
}

// ─── Jira Field Mapping ──────────────────────────────────────────────────────

export function severityToJiraPriority(severity: string): string {
  switch (severity) {
    case "critical": return "Blocker";
    case "high": return "Critical";
    case "medium": return "Major";
    case "low": return "Minor";
    default: return "Minor";
  }
}

export function buildJiraDescription(finding: ScanFinding, targetUrl: string): string {
  const lines: string[] = [];

  lines.push(`h3. ${finding.title}`);
  lines.push(``);
  lines.push(`*Severity:* ${finding.severity.toUpperCase()}`);
  lines.push(`*Category:* ${finding.category}`);
  lines.push(`*Target:* ${targetUrl}`);
  if (finding.cweId) lines.push(`*CWE:* [${finding.cweId}|https://cwe.mitre.org/data/definitions/${finding.cweId.replace("CWE-", "")}.html]`);
  if (finding.owaspCategory) lines.push(`*OWASP:* ${finding.owaspCategory}`);

  if (finding.cvssScore && finding.cvssVector) {
    lines.push(``);
    lines.push(`h4. CVSS Score`);
    lines.push(`*Score:* ${Number(finding.cvssScore).toFixed(1)} — {{${finding.cvssVector}}}`);
  }

  if (finding.description) {
    lines.push(``);
    lines.push(`h4. Description`);
    lines.push(finding.description);
  }

  const impact = finding.businessImpact as BusinessImpact | null;
  if (impact) {
    lines.push(``);
    lines.push(`h4. Business Impact`);
    lines.push(`|| Dimension || Rating ||`);
    lines.push(`| Financial | ${impact.financial} |`);
    lines.push(`| Operational | ${impact.operational} |`);
    lines.push(`| Reputational | ${impact.reputational} |`);
    lines.push(`| Legal | ${impact.legal} |`);
    lines.push(`_${impact.rationale}_`);
  }

  if (finding.recommendation) {
    lines.push(``);
    lines.push(`h4. Recommendation`);
    lines.push(finding.recommendation);
  }

  const poc = finding.poc as { curlCommand?: string; reproductionSteps?: string[] } | null;
  if (poc) {
    if (poc.curlCommand) {
      lines.push(``);
      lines.push(`h4. Proof of Concept`);
      lines.push(`{code:bash}`);
      lines.push(poc.curlCommand);
      lines.push(`{code}`);
    }
    if (poc.reproductionSteps && poc.reproductionSteps.length > 0) {
      lines.push(``);
      lines.push(`h4. Reproduction Steps`);
      poc.reproductionSteps.forEach((step, i) => {
        lines.push(`# ${step}`);
      });
    }
  }

  const techniques = finding.attackTechniques as AttackTechnique[] | null;
  if (techniques && techniques.length > 0) {
    lines.push(``);
    lines.push(`h4. MITRE ATT&CK`);
    for (const t of techniques) {
      lines.push(`* [${t.techniqueId}|https://attack.mitre.org/techniques/${t.techniqueId}/] — ${t.techniqueName} (${t.tactic})`);
    }
  }

  lines.push(``);
  lines.push(`----`);
  lines.push(`_Generated by Ghoststrike on ${new Date().toISOString().split("T")[0]}_`);

  return lines.join("\n");
}

export function buildJiraLabels(finding: ScanFinding, extraLabels: string[] = []): string[] {
  const labels = ["ghoststrike", "security", ...extraLabels];
  if (finding.owaspCategory) labels.push(finding.owaspCategory.split(" ")[0]);
  if (finding.cweId) labels.push(finding.cweId);
  return [...new Set(labels)];
}

/** Generate a stable hash for a finding based on title + category for deduplication */
export function findingStableId(finding: ScanFinding, targetUrl: string): string {
  const raw = `${targetUrl}|${finding.category}|${finding.title}`;
  let hash = 0;
  for (let i = 0; i < raw.length; i++) {
    const char = raw.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return `GS-${Math.abs(hash).toString(36)}`;
}

// ─── Jira API Client ─────────────────────────────────────────────────────────

async function jiraRequest(
  config: JiraConfig,
  path: string,
  method: string = "GET",
  body?: object,
): Promise<{ status: number; data: any }> {
  const url = `${config.baseUrl}/rest/api/3${path}`;
  const auth = Buffer.from(`${config.email}:${config.apiToken}`).toString("base64");

  const response = await fetch(url, {
    method,
    headers: {
      "Authorization": `Basic ${auth}`,
      "Content-Type": "application/json",
      "Accept": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  const data = response.headers.get("content-type")?.includes("json")
    ? await response.json()
    : await response.text();

  return { status: response.status, data };
}

async function searchJiraForExisting(
  config: JiraConfig,
  findingTitle: string,
): Promise<{ key: string; status: string } | null> {
  if (!config.deduplication) return null;

  const jql = `project = "${config.projectKey}" AND summary ~ "${findingTitle.replace(/"/g, '\\"').substring(0, 100)}" ORDER BY created DESC`;
  try {
    const { status, data } = await jiraRequest(config, `/search?jql=${encodeURIComponent(jql)}&maxResults=1`);
    if (status === 200 && data.issues?.length > 0) {
      const issue = data.issues[0];
      return { key: issue.key, status: issue.fields.status.name.toLowerCase() };
    }
  } catch {
    // search failed
  }
  return null;
}

/** Push a single finding to Jira */
export async function pushFindingToJira(
  config: JiraConfig,
  finding: ScanFinding,
  targetUrl: string,
  dryRun: boolean = false,
): Promise<TicketResult> {
  if (!meetsMinSeverity(finding.severity, config.minSeverity)) {
    return { provider: "jira", action: "skipped", findingTitle: finding.title, reason: `Below ${config.minSeverity} threshold` };
  }

  const existing = await searchJiraForExisting(config, finding.title);

  if (existing) {
    if (existing.status === "done" || existing.status === "closed" || existing.status === "resolved") {
      if (config.reopenResolved) {
        if (dryRun) return { provider: "jira", action: "reopened", findingTitle: finding.title, ticketKey: existing.key, reason: "dry-run" };
        try {
          await jiraRequest(config, `/issue/${existing.key}/comment`, "POST", {
            body: { type: "doc", version: 1, content: [{ type: "paragraph", content: [{ type: "text", text: `Finding re-detected by Ghoststrike scan on ${new Date().toISOString().split("T")[0]}. Please re-investigate.` }] }] },
          });
        } catch { /* comment failed */ }
        return { provider: "jira", action: "reopened", findingTitle: finding.title, ticketKey: existing.key, ticketUrl: `${config.baseUrl}/browse/${existing.key}` };
      }
    } else {
      if (dryRun) return { provider: "jira", action: "commented", findingTitle: finding.title, ticketKey: existing.key, reason: "dry-run" };
      try {
        await jiraRequest(config, `/issue/${existing.key}/comment`, "POST", {
          body: { type: "doc", version: 1, content: [{ type: "paragraph", content: [{ type: "text", text: `Finding still present in Ghoststrike scan on ${new Date().toISOString().split("T")[0]}.` }] }] },
        });
      } catch { /* comment failed */ }
      return { provider: "jira", action: "commented", findingTitle: finding.title, ticketKey: existing.key, ticketUrl: `${config.baseUrl}/browse/${existing.key}` };
    }
  }

  if (dryRun) {
    return { provider: "jira", action: "created", findingTitle: finding.title, reason: "dry-run" };
  }

  const issueBody = {
    fields: {
      project: { key: config.projectKey },
      summary: `[Ghoststrike] ${finding.title}`.substring(0, 255),
      description: {
        type: "doc", version: 1,
        content: [{ type: "paragraph", content: [{ type: "text", text: buildJiraDescription(finding, targetUrl) }] }],
      },
      issuetype: { name: config.issueType ?? "Bug" },
      priority: { name: severityToJiraPriority(finding.severity) },
      labels: buildJiraLabels(finding, config.labels),
    },
  };

  try {
    const { status, data } = await jiraRequest(config, "/issue", "POST", issueBody);
    if (status === 201 || status === 200) {
      return { provider: "jira", action: "created", findingTitle: finding.title, ticketKey: data.key, ticketUrl: `${config.baseUrl}/browse/${data.key}` };
    }
    return { provider: "jira", action: "skipped", findingTitle: finding.title, reason: `Jira API error: ${status}` };
  } catch (err: any) {
    return { provider: "jira", action: "skipped", findingTitle: finding.title, reason: `Jira API error: ${err.message}` };
  }
}

// ─── GitHub Issues Client ─────────────────────────────────────────────────────

export async function pushFindingToGitHub(
  config: GitHubConfig,
  finding: ScanFinding,
  targetUrl: string,
  dryRun: boolean = false,
): Promise<TicketResult> {
  if (!meetsMinSeverity(finding.severity, config.minSeverity)) {
    return { provider: "github", action: "skipped", findingTitle: finding.title, reason: `Below ${config.minSeverity} threshold` };
  }

  if (dryRun) {
    return { provider: "github", action: "created", findingTitle: finding.title, reason: "dry-run" };
  }

  const body = [
    `## ${finding.title}`,
    ``,
    `**Severity:** ${finding.severity.toUpperCase()}`,
    `**Category:** ${finding.category}`,
    `**Target:** ${targetUrl}`,
    finding.cweId ? `**CWE:** [${finding.cweId}](https://cwe.mitre.org/data/definitions/${finding.cweId.replace("CWE-", "")}.html)` : "",
    finding.description ? `\n### Description\n${finding.description}` : "",
    finding.recommendation ? `\n### Recommendation\n${finding.recommendation}` : "",
    `\n---\n_Generated by Ghoststrike_`,
  ].filter(Boolean).join("\n");

  try {
    const response = await fetch(`https://api.github.com/repos/${config.repo}/issues`, {
      method: "POST",
      headers: {
        "Authorization": `token ${config.token}`,
        "Content-Type": "application/json",
        "Accept": "application/vnd.github.v3+json",
      },
      body: JSON.stringify({
        title: `[Ghoststrike] ${finding.title}`.substring(0, 255),
        body,
        labels: ["ghoststrike", "security", ...(config.labels ?? [])],
      }),
    });

    if (response.ok) {
      const data = await response.json() as { number: number; html_url: string };
      return { provider: "github", action: "created", findingTitle: finding.title, ticketKey: `#${data.number}`, ticketUrl: data.html_url };
    }
    return { provider: "github", action: "skipped", findingTitle: finding.title, reason: `GitHub API error: ${response.status}` };
  } catch (err: any) {
    return { provider: "github", action: "skipped", findingTitle: finding.title, reason: `GitHub API error: ${err.message}` };
  }
}

// ─── Linear Client ────────────────────────────────────────────────────────────

export async function pushFindingToLinear(
  config: LinearConfig,
  finding: ScanFinding,
  targetUrl: string,
  dryRun: boolean = false,
): Promise<TicketResult> {
  if (!meetsMinSeverity(finding.severity, config.minSeverity)) {
    return { provider: "linear", action: "skipped", findingTitle: finding.title, reason: `Below ${config.minSeverity} threshold` };
  }

  if (dryRun) {
    return { provider: "linear", action: "created", findingTitle: finding.title, reason: "dry-run" };
  }

  const description = [
    `**Severity:** ${finding.severity.toUpperCase()}`,
    `**Category:** ${finding.category}`,
    `**Target:** ${targetUrl}`,
    finding.cweId ? `**CWE:** [${finding.cweId}](https://cwe.mitre.org/data/definitions/${finding.cweId.replace("CWE-", "")}.html)` : "",
    finding.description ? `\n### Description\n${finding.description}` : "",
    finding.recommendation ? `\n### Recommendation\n${finding.recommendation}` : "",
    `\n---\n_Generated by Ghoststrike_`,
  ].filter(Boolean).join("\n");

  const mutation = `mutation IssueCreate($input: IssueCreateInput!) {
    issueCreate(input: $input) {
      success
      issue { id identifier url }
    }
  }`;

  const variables = {
    input: {
      teamId: config.teamId,
      title: `[Ghoststrike] ${finding.title}`.substring(0, 255),
      description,
      priority: finding.severity === "critical" ? 1 : finding.severity === "high" ? 2 : finding.severity === "medium" ? 3 : 4,
    },
  };

  try {
    const response = await fetch("https://api.linear.app/graphql", {
      method: "POST",
      headers: {
        "Authorization": config.apiKey,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query: mutation, variables }),
    });

    if (response.ok) {
      const data = await response.json() as any;
      const issue = data?.data?.issueCreate?.issue;
      if (issue) {
        return { provider: "linear", action: "created", findingTitle: finding.title, ticketKey: issue.identifier, ticketUrl: issue.url };
      }
    }
    return { provider: "linear", action: "skipped", findingTitle: finding.title, reason: `Linear API error: ${response.status}` };
  } catch (err: any) {
    return { provider: "linear", action: "skipped", findingTitle: finding.title, reason: `Linear API error: ${err.message}` };
  }
}

// ─── Orchestrator ─────────────────────────────────────────────────────────────

/** Push all findings to all configured ticketing integrations */
export async function pushFindingsToTicketing(
  config: IntegrationsConfig,
  findings: ScanFinding[],
  targetUrl: string,
  dryRun: boolean = false,
): Promise<TicketResult[]> {
  const results: TicketResult[] = [];

  for (const finding of findings) {
    if (config.jira?.enabled) {
      results.push(await pushFindingToJira(config.jira, finding, targetUrl, dryRun));
    }

    if (config.github?.enabled) {
      results.push(await pushFindingToGitHub(config.github, finding, targetUrl, dryRun));
    }

    if (config.linear?.enabled) {
      results.push(await pushFindingToLinear(config.linear, finding, targetUrl, dryRun));
    }
  }

  return results;
}
